version: '3.8'

services:
  mongodb:
    image: mongo:5.0.15
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: vylex
      MONGO_INITDB_ROOT_PASSWORD: cledsonLeite
      MONGO_INITDB_DATABASE: vylex
    volumes:
      - mongo_data:/data/db
    command: ["mongod", "--auth"]

volumes:
  mongo_data:
